# Main of MTG Modern Infect T2 kill chance calculator
import pandas as pd
import matplotlib.pyplot as plt
import os
import sys
import converter
import classes

#Setting directory
os.chdir(os.path.dirname(sys.argv[0]))

def Get_Deck(file):
    #Getting the list from the txt file generated by goldfish.
    df = open(file).read().splitlines()
    deck = []
    for line in df:
        # Goldfish add sidebord after an empty line. As we do not want sideboard the for loop breaks after empty line.
        if line != "":
            for i in range(0,int(line[0])):
                deck.append(line[2:])
        else:
            break
    #Saving is as a list to pass it to convertet
    return(deck)


Deck = Get_Deck("Deck.txt")

# Start simulation #1
Test1 = classes.Test()
Test1.Start_test(Deck)
Test1.Test_go(i = 10000, handsize = 7) # Test object, number of itterations, handsize

# Printing the results of the test. 
print(Test1)
pd.Series(Test1.poison).value_counts().sort_index().plot(kind='bar')
plt.show()



